Repository PrivSec-dev/privsec.dev, pull requests merged in 2023-11, with the labels that each got.

#172 Add banking app reports 310, 312-316
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#173 Add banking app report 320
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#174 Opt out of Chrome's Topics API
  static/_headers
Labels: [s] enhancement

#175 Add banking app reports 321-323
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#179 Add Slovakia and banking app reports 325-329
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#171 Update carrier shenanigans information and remove inaccurate information
  content/posts/android/Android Tips.md
Labels: [c] update existing

#180 Update banking app report 243
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#181 Update banking app report 53
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#182 Update gist and possible solutions links.
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] cleanup
