Repository PrivSec-dev/privsec.dev, pull requests merged in 2024-04, with the labels that each got.

#218 Update banking app report 382, add 424
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#219 Add banking app reports 425, 427-429
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#220 Fix typo
  content/posts/knowledge/FLOSS Security.md
Labels: [c] cleanup

#223 fix(linux/Docker and OCI Hardening): correction on no_new_privs option
  content/posts/linux/Docker and OCI Hardening.md
Labels: [c] cleanup

#224 Add banking app reports 432-436, 438 and 439, update names and sanitize links
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#225 Add banking app report 440
  content/posts/android/Banking Applications compatibility with GrapheneOS.md
Labels: [c] update existing

#222 ChromeOS's Questionable Encryption
  content/posts/knowledge/ChromeOS Questionable Encryption/google-login.jpg
  content/posts/knowledge/ChromeOS Questionable Encryption/index.md
Labels: [c] new content
